from alpine:3.16

RUN addgroup -S user && adduser -S user -G user -s /bin/ash
RUN apk --update add --no-cache bash openssl tcl tcl-dev git
RUN apk --update add --no-cache --virtual egg-deps wget ca-certificates make tar gpgme build-base openssl-dev 
RUN git clone https://github.com/eggheads/eggdrop eggdropgit
WORKDIR eggdropgit
RUN ./configure && make config && make && make install DEST=/home/user/eggdrop
WORKDIR /home/user/eggdrop
COPY entrypoint.sh /home/user/eggdrop
COPY eggdrop.user /home/user/eggdrop
RUN chown -R user:user /home/user/eggdrop
RUN chmod +x /home/user/eggdrop/entrypoint.sh
CMD /home/user/eggdrop/entrypoint.sh
