from fedora:34

RUN adduser user
RUN yum install -y tcl tcl-devel openssl openssl-devel gcc tar wget make git
RUN git clone https://github.com/eggheads/eggdrop eggdropgit
WORKDIR eggdropgit
RUN ./configure && make config && make && make install DEST=/home/user/eggdrop
WORKDIR /home/user/eggdrop
COPY entrypoint.sh /home/user/eggdrop
COPY eggdrop.user /home/user/eggdrop
RUN chown -R user:user /home/user/eggdrop
RUN chmod +x /home/user/eggdrop/entrypoint.sh
CMD /home/user/eggdrop/entrypoint.sh
