name: OS Testing

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  Ubuntu_22_04:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_ubuntu_22 --tag eggdrop:ubuntu22
    - name: Run Docker image
      run: docker run -dti -v ${GITHUB_WORKSPACE}:/eggdata --name eggubun20 eggdrop:ubuntu22

  Ubuntu_20_04:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_ubuntu_20 --tag eggdrop:ubuntu20
    - name: Run Docker image
      run: docker run -dti -v ${GITHUB_WORKSPACE}:/eggdata --name eggubun20 eggdrop:ubuntu20

  Ubuntu_18_04:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_ubuntu_18 --tag eggdrop:ubuntu18
    - name: Run Docker image
      run: docker run -dti -v ${GITHUB_WORKSPACE}:/eggdata --name eggubun18 eggdrop:ubuntu18

  Debian_Buster:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_debian_9 --tag eggdrop:debian9
    - name: Run Docker image
      run: docker run -dti -v ${GITHUB_WORKSPACE}:/eggdata --name eggdeb9 eggdrop:debian9

  Debian_Stretch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_debian_10 --tag eggdrop:debian10
    - name: Run Docker image
      run: docker run -dti -v ${GITHUB_WORKSPACE}:/eggdata --name eggdeb10 eggdrop:debian10

  Debian_Bullseye:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_debian_11 --tag eggdrop:debian11
    - name: Run Docker image
      run: docker run -dti -v ${GITHUB_WORKSPACE}:/eggdata --name eggdeb11 eggdrop:debian11

  Debian_Sid:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_debian_sid --tag eggdrop:debiansid
    - name: Run Docker image
      run: docker run -dti -v ${GITHUB_WORKSPACE}:/eggdata --name eggdebsid eggdrop:debiansid

  Centos_7:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_centos_7 --tag eggdrop:centos7
    - name: Run Docker image
      run: docker run -dti -v ${GITHUB_WORKSPACE}:/eggdata --name eggcent7 eggdrop:centos7

  Fedora_34:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_fedora_34 --tag eggdrop:fedora34
    - name: Run Docker image
      run: docker run -dti -v ${GITHUB_WORKSPACE}:/eggdata --name eggfed34 eggdrop:fedora34

  Fedora_35:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_fedora_35 --tag eggdrop:fedora35
    - name: Run Docker image
      run: docker run -dti -v ${GITHUB_WORKSPACE}:/eggdata --name eggfed35 eggdrop:fedora35

  Fedora_36:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_fedora_36 --tag eggdrop:fedora36
    - name: Run Docker image
      run: docker run -dti -v ${GITHUB_WORKSPACE}:/eggdata --name eggfed36 eggdrop:fedora36

  Fedora_Rawhide:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_fedora_raw --tag eggdrop:fedoraraw
    - name: Run Docker image
      run: docker run -dti -v ${GITHUB_WORKSPACE}:/eggdata --name eggfedraw eggdrop:fedoraraw

  Opensuse_15_4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_opensuse_15.4 --tag eggdrop:opensuse154
    - name: Run Docker image
      run: docker run -dti -v ${GITHUB_WORKSPACE}:/eggdata --name eggopensuse154 eggdrop:opensuse154

  Alpine_316:
    runs-on: ubuntu:latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_alpine_316 --tag eggdrop:alpine316
    - name: Run Docker image
      run: docker run -dti -v ${GITHUB_WORKSPACE}:/eggdata --name eggalpien316 eggdrop:alpine316


  FreeBSD:
    runs-on: macos-12
    name: FreeBSD
    steps:
    - uses: actions/checkout@v2
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.1.6
      with:
        usesh: true
        sync: sshfs
        prepare: pkg install -y git tcl86 gcc
        run: |
          git clone https://github.com/eggheads/eggdrop eggdropgit
          cd eggdropgit
          ./configure
          make config
          make
          make install
          cd ~/eggdrop
