name: Docker Image CI

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  Ubuntu_20_04:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_ubuntu_20 --tag eggdrop:ubuntu20
    - name: Run Docker image
      run: docker run -di -v ${GITHUB_WORKSPACE}:/eggdata --publish 3333:3333 --name eggfoo eggdrop:ubuntu20
    - name: omgwhy
      run: sleep 3; ls -al ${GITHUB_WORKSPACE}
#    - name: telnet
#      run: bash -c '{ echo "testuser1"; echo "eggdrop"; sleep 2; echo "die";} | telnet 127.0.0.1 3333'
    - name: Verify PID file exists
      run: ls -al ${GITHUB_WORKSPACE}; cat ${GITHUB_WORKSPACE}/pid.Lamestbot
    - name: Death to eggs
      run: docker stop $(docker ps -q)
