name: Docker Image CI

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  Ubuntu_20_04:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_ubuntu_20 --tag eggdrop:ubuntu20
    - name: Run Docker image
      run: docker run -ti -v ${GITHUB_WORKSPACE}:/eggdata --publish 3333:3333 --name eggubun20 eggdrop:ubuntu20

  Ubuntu_18_04:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_ubuntu_18 --tag eggdrop:ubuntu18
    - name: Run Docker image
      run: docker run -ti -v ${GITHUB_WORKSPACE}:/eggdata --publish 3333:3333 --name eggubun18 eggdrop:ubuntu18

  Debian_Buster:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_debian_9 --tag eggdrop:debian9
    - name: Run Docker image
      run: docker run -ti -v ${GITHUB_WORKSPACE}:/eggdata --publish 3333:3333 --name eggdeb9 eggdrop:debian9

  Debian_Stretch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_debian_10 --tag eggdrop:debian10
    - name: Run Docker image
      run: docker run -ti -v ${GITHUB_WORKSPACE}:/eggdata --publish 3333:3333 --name eggdeb10 eggdrop:debian10

  Debian_Bullseye:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_debian_11 --tag eggdrop:debian11
    - name: Run Docker image
      run: docker run -ti -v ${GITHUB_WORKSPACE}:/eggdata --publish 3333:3333 --name eggdeb11 eggdrop:debian11

  Debian_Sid:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_debian_sid --tag eggdrop:debiansid
    - name: Run Docker image
      run: docker run -ti -v ${GITHUB_WORKSPACE}:/eggdata --publish 3333:3333 --name eggdebsid eggdrop:debiansid
