name: Docker Image CI

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  Ubuntu_20_04:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_ubuntu_20 --tag eggdrop:ubuntu20
    - name: Run Docker image
      run: docker run -di --name eggfoo eggdrop:ubuntu20
    - name: Is it running?
      run: if [ -a /home/user/eggdrop/pid.Lamestbot ]; then cat /home/user/eggdrop/pid.Lamestbot; else echo "Not running!"; fi
    - name: Death to eggs
      run: docker stop $(docker ps -q)
