name: Docker Image CI

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  Ubuntu_20_04:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/Dockerfile_ubuntu_20 --tag eggdrop:ubuntu20
    - name: Run Docker image
      run: docker run -di -v ${GITHUB_WORKSPACE}:/data --name eggfoo eggdrop:ubuntu20
    - name: Verify PID file exists
      run: cat ${GITHUB_WORKSPACE}/pidtest
    - name: Death to eggs
      run: docker stop $(docker ps -q)
